#!/bin/sh -e
#
# Copyright © 2018-2023 Johnothan King. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# jlocate -- Multi-process implementation of locate(1)
#

# Load the configuration
. /etc/jlocate.conf

# This must be run as root
if [ ! "$1" ]; then
	echo 'You must provide jlocate with a query!'
	exit 1
fi

# Read compressed databases
if [ -f "$FCODES.$EXTENSION" ]; then
	"$UNCOMPRESS" -c "$FCODES.$EXTENSION" | grep "$@"

# Read uncompressed databases
elif [ -f "$FCODES" ]; then
	exec grep "$@" "$FCODES"

# Fallback
else
	echo 'Please run `jupdatedb` to make the file database for jlocate.'
	exit 1
fi
