#!/bin/sh
#
# Copyright (c) 2018 Johnothan King. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# updatedb - Update the locate(1) database
#

# Load the configuration
. /etc/jlocate.rc

# Make sure $FDIR exists and is a clean directory
mkdir -p ${FDIR}
rm -f ${FDIR}/*

# Build the database using jfork(1) to run multiple instances of find(1)
for dir in `ls / | sed 's/tmp//g' | sed 's/proc//g' | sed 's/dev//g' | sed 's/sys//g'`; do
	jfork "find /${dir} > ${TMPDIR}/jlocate-${dir}.tdb"
done

# Wait until all instances of find(1) are done searching
until [ "`pgrep -x find`" = "" ]; do
	false
done

# Prune paths if needed
if [ "$PRUNE_PATHS" != "" ]; then
	cat ${TMPDIR}/jlocate-*.tdb | grep -Ev "`echo $PRUNE_PATHS $PRUNE_NAMES | sed 's: :|:g'`" > ${FCODES}
else
	cat ${TMPDIR}/jlocate-*.tdb > ${FCODES}
fi

# Done to prevent bugs
rm -f ${TMPDIR}/jlocate*.tdb

# Optional compression (configurable)
if [ "$1" = -c ]; then
	${COMPRESS} ${COMPRESSFLAGS} ${FCODES}
fi

# Done for security purposes
chown nobody:wheel ${FCODES}*
chmod 0440 ${FCODES}*

exit 0
